#!/usr/bin/env bash
#
# Build a MINIFIED RELEASE Android APK and cold-start it on a connected device.
#
# Why this exists
# ---------------
# OpenDraft pinned tauri to 2.10.3 (commit c1a5dd1) because v0.17.0 cold-started
# and died on Android 15 — a SIGABRT from a panic inside the Rust .so.
#
# Root cause: wry 0.55.0 added a JNI call to `WryActivity.getId()` but did not
# add `getId` to its ProGuard keep rules, so R8 was free to strip or rename it
# when minifying. The JNI lookup then fails, Rust panics, and `panic = "abort"`
# turns that into SIGABRT. wry 0.55.1 added the missing keep rule.
#
# THE POINT: this only reproduces in a *minified release* build. A debug build
# has isMinifyEnabled = false, R8 never runs, and the bug is invisible. Running
# `tauri android dev` proves nothing about this crash.
#
# Usage
#   ./test-script/android-release-smoke-test.sh              # build, verify, install, launch
#   ./test-script/android-release-smoke-test.sh --verify-only # build + static checks, no device
#
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

VERIFY_ONLY=0
[[ "${1:-}" == "--verify-only" ]] && VERIFY_ONLY=1

APP_ID="com.proteus.opendraft"
GEN="$PROJECT_ROOT/src-tauri/gen/android"
APK="$GEN/app/build/outputs/apk/universal/release/app-universal-release.apk"
MAPPING="$GEN/app/build/outputs/mapping/universalRelease/mapping.txt"
GENERATED_PRO="$GEN/app/src/main/java/com/proteus/opendraft/generated/proguard-wry.pro"

red()   { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
bold()  { printf '\033[1m%s\033[0m\n' "$*"; }
die()   { red "ERROR: $*"; exit 1; }

# ── 1. Preflight ───────────────────────────────────────────────────────────
bold "== Preflight =="

export ANDROID_HOME="${ANDROID_HOME:-$HOME/Library/Android/sdk}"
[[ -d "$ANDROID_HOME" ]] || die "Android SDK not found at $ANDROID_HOME. Set ANDROID_HOME."

ADB="$ANDROID_HOME/platform-tools/adb"
[[ -x "$ADB" ]] || die "adb not found at $ADB"

# Tauri needs NDK_HOME. Pick the highest installed NDK if it is not already set.
if [[ -z "${NDK_HOME:-}" ]]; then
  NDK_DIR="$ANDROID_HOME/ndk"
  [[ -d "$NDK_DIR" ]] || die "No NDK under $NDK_DIR. Install NDK 27 via Android Studio."
  NDK_VER="$(ls -1 "$NDK_DIR" | sort -V | tail -1)"
  export NDK_HOME="$NDK_DIR/$NDK_VER"
fi
echo "ANDROID_HOME = $ANDROID_HOME"
echo "NDK_HOME     = $NDK_HOME"

for t in aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android; do
  rustup target list --installed | grep -qx "$t" || die "Missing Rust target $t (rustup target add $t)"
done
green "Rust Android targets present"

[[ -d "$GEN" ]] || die "$GEN missing. Run: npx --prefix frontend tauri android init"

# The release buildType must actually minify, or this test is meaningless.
grep -q "isMinifyEnabled = true" "$GEN/app/build.gradle.kts" \
  || die "release buildType is not minified — this test cannot reproduce the bug."
green "release buildType has isMinifyEnabled = true"

grep -q "signingConfigs" "$GEN/app/build.gradle.kts" || die \
  "No signingConfigs in build.gradle.kts. Re-apply the CI patch (see the
   'Configure release signing' step in .github/workflows/release.yml), or
   delete src-tauri/gen/android and re-run 'tauri android init'."

# ── 2. Signing keystore ────────────────────────────────────────────────────
# Release builds must be signed to install. A throwaway keystore is fine — this
# is a crash test, not a distributable artifact.
bold "== Signing =="
KEYSTORE="${KEYSTORE_PATH:-$PROJECT_ROOT/test-script/output/smoke-test.keystore}"
mkdir -p "$(dirname "$KEYSTORE")"
if [[ ! -f "$KEYSTORE" ]]; then
  echo "Generating a throwaway keystore at $KEYSTORE"
  keytool -genkey -v -keystore "$KEYSTORE" -alias opendraft \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -dname "CN=OpenDraft SmokeTest, O=OpenDraft" \
    -storepass opendraft -keypass opendraft >/dev/null 2>&1 \
    || die "keytool failed to create the keystore"
fi
export KEYSTORE_PATH="$KEYSTORE"
export KEYSTORE_PASSWORD="${KEYSTORE_PASSWORD:-opendraft}"
export KEY_ALIAS="${KEY_ALIAS:-opendraft}"
export KEY_PASSWORD="${KEY_PASSWORD:-opendraft}"
green "Keystore ready"

# ── 3. Sync tracked Android sources ────────────────────────────────────────
# src-tauri/gen/android is gitignored and regenerated by `tauri android init`,
# so the project's real Kotlin lives in src-tauri/android-src and CI copies it
# over the generated stubs. Do the same here, or a local build silently tests
# whatever Kotlin happened to be lying around.
bold "== Syncing android-src =="
cp "$PROJECT_ROOT/src-tauri/android-src/MainActivity.kt" \
   "$GEN/app/src/main/java/com/proteus/opendraft/MainActivity.kt" \
  || die "Could not copy MainActivity.kt"
[[ -f "$PROJECT_ROOT/src-tauri/android-src/jni-keep-rules.pro" ]] && \
  cp "$PROJECT_ROOT/src-tauri/android-src/jni-keep-rules.pro" "$GEN/app/jni-keep-rules.pro"
green "android-src synced into gen/android"

# ── 4. Build ───────────────────────────────────────────────────────────────
bold "== Building release APK (this takes a while: 4 Rust targets + R8) =="
# Invoked from the project root so tauri.conf.json's beforeBuildCommand
# ("cd frontend && npm run build") resolves, exactly as CI does it.
npx --prefix frontend tauri android build --apk \
  || die "Android build failed"

[[ -f "$APK" ]] || die "Expected APK not found at $APK"
green "APK built: $APK"

# ── 5. Static verification — the part that needs no device ────────────────
bold "== Verifying the ProGuard fix =="

if [[ -f "$GENERATED_PRO" ]]; then
  if grep -q "getId" "$GENERATED_PRO"; then
    green "PASS  generated proguard-wry.pro keeps getId (wry >= 0.55.1)"
  else
    red   "FAIL  generated proguard-wry.pro has NO getId keep rule."
    red   "      This is the wry 0.55.0 file. R8 may strip WryActivity.getId()"
    red   "      and the app will SIGABRT on cold start."
    red   "      Check: grep '^wry' src-tauri/Cargo.lock  (want 0.55.1+)"
    exit 1
  fi
else
  red "WARN  $GENERATED_PRO not found — could not check the keep rule."
fi

# R8's mapping file is the ground truth: if getId was renamed or dropped, the
# JNI lookup fails at runtime. A kept method maps to its own name.
#
# Entries look like:   1:8:int getId():49:49 -> getId
# so the test is "a getId() signature whose mapped name is still getId".
if [[ -f "$MAPPING" ]]; then
  # Extract just the WryActivity class block: everything after its header line
  # up to the next class line.  R8 interleaves unindented `# {...}` metadata
  # comments, so those must not be treated as the end of the block.
  WRY_BLOCK="$(awk -v cls="$APP_ID.WryActivity ->" '
    index($0, cls) == 1 { inblock = 1; next }
    inblock && /^[^[:space:]#]/ { inblock = 0 }
    inblock { print }
  ' "$MAPPING")"

  if [[ -z "$WRY_BLOCK" ]]; then
    red "WARN  No WryActivity entry in the R8 mapping — cannot verify."
  elif grep -qE 'getId\(\).*-> getId$' <<<"$WRY_BLOCK"; then
    green "PASS  R8 mapping keeps WryActivity.getId() unobfuscated"
  else
    red "FAIL  WryActivity.getId() is absent or renamed in the R8 mapping."
    red "      R8 stripped the method the Rust side looks up by name via JNI,"
    red "      which is the exact cold-start SIGABRT this test is for."
    echo "      Methods R8 kept on WryActivity:"
    grep -oE '\-> [A-Za-z_][A-Za-z0-9_]*$' <<<"$WRY_BLOCK" | sort -u | sed 's/^/        /'
    exit 1
  fi
else
  red "WARN  No R8 mapping at $MAPPING — skipping the strongest check."
fi

if [[ "$VERIFY_ONLY" == "1" ]]; then
  bold "== --verify-only: static checks passed, skipping device run =="
  exit 0
fi

# ── 6. Install and cold-start ──────────────────────────────────────────────
bold "== Device =="
DEVICES="$("$ADB" devices | awk 'NR>1 && $2=="device" {print $1}')"
[[ -n "$DEVICES" ]] || die "No device attached. Enable USB debugging and reconnect.
   (Static checks above already passed — re-run with --verify-only to skip this.)"

SERIAL="$(echo "$DEVICES" | head -1)"
RELEASE="$("$ADB" -s "$SERIAL" shell getprop ro.build.version.release | tr -d '\r')"
MODEL="$("$ADB" -s "$SERIAL" shell getprop ro.product.model | tr -d '\r')"
echo "Device: $MODEL (Android $RELEASE, $SERIAL)"
[[ "${RELEASE%%.*}" -ge 15 ]] 2>/dev/null \
  || red "NOTE  The crash was reported on Android 15. This device is $RELEASE."

# Uninstall first: a signature mismatch against an existing install fails, and a
# warm start would not exercise the cold-start path the bug lives in.
"$ADB" -s "$SERIAL" uninstall "$APP_ID" >/dev/null 2>&1 || true
"$ADB" -s "$SERIAL" install -r "$APK" || die "adb install failed"
green "Installed"

"$ADB" -s "$SERIAL" logcat -c 2>/dev/null || true
LOG="$PROJECT_ROOT/test-script/output/android-smoke-$(date +%Y%m%d-%H%M%S).log"
"$ADB" -s "$SERIAL" logcat > "$LOG" 2>&1 &
LOGPID=$!
trap 'kill "$LOGPID" 2>/dev/null || true' EXIT

bold "== Cold start =="
"$ADB" -s "$SERIAL" shell am start -n "$APP_ID/.MainActivity" >/dev/null \
  || die "Failed to launch $APP_ID/.MainActivity"

# Long enough for the WebView and the Rust side to come up and abort if broken.
sleep 15

PID="$("$ADB" -s "$SERIAL" shell pidof "$APP_ID" | tr -d '\r' || true)"
kill "$LOGPID" 2>/dev/null || true

echo
if [[ -n "$PID" ]]; then
  green "PASS  App is still running after 15s (pid $PID) — no cold-start crash."
else
  red "FAIL  App is NOT running — it exited during startup."
  echo
  bold "Crash lines from logcat:"
  grep -iE "SIGABRT|FATAL|libopendraft|panicked|DEBUG   :|NoSuchMethod" "$LOG" | head -40 || true
  echo
  echo "Full log: $LOG"
  echo "Symbolicate a native stack with:"
  echo "  \$NDK_HOME/ndk-stack -sym src-tauri/target/aarch64-linux-android/release -dump $LOG"
  exit 1
fi

echo "Full log: $LOG"
bold "Now exercise it by hand: type in a script, background/foreground the app, rotate."
